# TEST ONE
## solution to questions

In [3]:
import numpy as np


In [4]:
import pandas as pd

In [5]:
import matplotlib as plt

SECTION 1


#Qn 1
A

#Qn 2
B

#Qn 3


#Qn 4
A

#Qn 5
B

#Qn 6
B

#Qn 7
C

#Qn 8
A 

#Qn 9
D

#Qn 10
10.(a)
A

10.(b)
(3)

SECTION 2

In [50]:
#Qn 2
p = (1,0)

(1, 2)

In [16]:
#Qn 4
#QN 4.1 an array x with (25,2,5)
x = np.ones([25,2,5])
x

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [

In [17]:
#4.2 shape of array x
x.shape

(25, 2, 5)

In [18]:
#4.3 transpose
x.T

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.,

In [19]:
# 4.4 norm
np.linalg.norm(x)

15.811388300841896

In [22]:
#Qn 5
X = np.array([[25,2],[5,26],[3,7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [23]:
#5.1 shape of X
X.shape

(3, 2)

In [24]:
#5.2 transpose of X
X.T

array([[25,  5,  3],
       [ 2, 26,  7]])

In [ ]:
#5.3
X = np.array([[]])

In [ ]:
#5.4
A = np.array([[3, 4], [5, 6], [7, 8]])
X = np.array([[25,2],[5,26],[3,7]])

In [35]:
#matrix multiplication of A and X
A*X

array([[ 75,   8],
       [ 25, 156],
       [ 21,  56]])

In [38]:
Z = (A*X)

In [40]:
#Qn 6
 #numpy array of a matrix
y = np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
y

array([[1. , 0.2, 0.5],
       [0.2, 1. , 0.8],
       [0.5, 0.8, 1. ]])

In [44]:
#6.(a) inversion of a matrix transpose
v = y.T 
v #my transpose

array([[1. , 0.2, 0.5],
       [0.2, 1. , 0.8],
       [0.5, 0.8, 1. ]])

In [45]:
np.linalg.inv(v) #inversion of amatrix transpose 

array([[ 1.56521739,  0.86956522, -1.47826087],
       [ 0.86956522,  3.26086957, -3.04347826],
       [-1.47826087, -3.04347826,  4.17391304]])

In [47]:
#6.(b)
#determinant of matrix y
np.linalg.det(y)

0.2299999999999999